/*
* generated by Xtext
*/
package org.xtext.verifier.slk.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.verifier.slk.services.SLEEKGrammarAccess;

public class SLEEKParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SLEEKGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.verifier.slk.parser.antlr.internal.InternalSLEEKParser createParser(XtextTokenStream stream) {
		return new org.xtext.verifier.slk.parser.antlr.internal.InternalSLEEKParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SLEEK";
	}
	
	public SLEEKGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SLEEKGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
