/*
* generated by Xtext
*/
package org.xtext.verifier.slk.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SLEEKAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/verifier/slk/parser/antlr/internal/InternalSLEEK.tokens");
	}
}
