/**
 * generated by Xtext
 */
package org.xtext.verifier.slk.validation;

import org.xtext.verifier.slk.validation.AbstractSLEEKValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SLEEKValidator extends AbstractSLEEKValidator {
}
