/*
 * generated by Xtext
 */
package org.xtext.verifier.slk.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SLEEKUiModule extends org.xtext.verifier.slk.ui.AbstractSLEEKUiModule {
	public SLEEKUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
