/*
 * generated by Xtext
 */
package org.xtext.verifier.slk.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.verifier.slk.ui.internal.SLEEKActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SLEEKExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SLEEKActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SLEEKActivator.getInstance().getInjector(SLEEKActivator.ORG_XTEXT_VERIFIER_SLK_SLEEK);
	}
	
}
