/*
* generated by Xtext
*/
package org.xtext.verifier.slk;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SLEEKUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.verifier.slk.ui.internal.SLEEKActivator.getInstance().getInjector("org.xtext.verifier.slk.SLEEK");
	}
	
}
