/**
 * generated by Xtext
 */
package org.xtext.verifier.slk.ui.contentassist;

import org.xtext.verifier.slk.ui.contentassist.AbstractSLEEKProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SLEEKProposalProvider extends AbstractSLEEKProposalProvider {
}
