/*
* generated by Xtext
*/
package org.xtext.verifier.slk;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SLEEKStandaloneSetup extends SLEEKStandaloneSetupGenerated{

	public static void doSetup() {
		new SLEEKStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

