/*
 * generated by Xtext
 */
package org.xtext.verifier.slk;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SLEEKRuntimeModule extends org.xtext.verifier.slk.AbstractSLEEKRuntimeModule {

}
