/*
* generated by Xtext
*/
package org.xtext.verifier.slk.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.verifier.slk.services.SLEEKGrammarAccess;

public class SLEEKParser extends AbstractContentAssistParser {
	
	@Inject
	private SLEEKGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.verifier.slk.ui.contentassist.antlr.internal.InternalSLEEKParser createParser() {
		org.xtext.verifier.slk.ui.contentassist.antlr.internal.InternalSLEEKParser result = new org.xtext.verifier.slk.ui.contentassist.antlr.internal.InternalSLEEKParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getArguAccess().getAlternatives(), "rule__Argu__Alternatives");
					put(grammarAccess.getDataAccess().getGroup(), "rule__Data__Group__0");
					put(grammarAccess.getLemmaAccess().getGroup(), "rule__Lemma__Group__0");
					put(grammarAccess.getPrecoditionAccess().getGroup(), "rule__Precodition__Group__0");
					put(grammarAccess.getArgumentAccess().getGroup(), "rule__Argument__Group__0");
					put(grammarAccess.getPrintAccess().getGroup(), "rule__Print__Group__0");
					put(grammarAccess.getSLEEKAccess().getKeywordsAssignment(), "rule__SLEEK__KeywordsAssignment");
					put(grammarAccess.getDataAccess().getNameAssignment_1(), "rule__Data__NameAssignment_1");
					put(grammarAccess.getLemmaAccess().getNameAssignment_1(), "rule__Lemma__NameAssignment_1");
					put(grammarAccess.getPrecoditionAccess().getNameAssignment_1(), "rule__Precodition__NameAssignment_1");
					put(grammarAccess.getArgumentAccess().getNameAssignment_1(), "rule__Argument__NameAssignment_1");
					put(grammarAccess.getPrintAccess().getNameAssignment_1(), "rule__Print__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.verifier.slk.ui.contentassist.antlr.internal.InternalSLEEKParser typedParser = (org.xtext.verifier.slk.ui.contentassist.antlr.internal.InternalSLEEKParser) parser;
			typedParser.entryRuleSLEEK();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SLEEKGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SLEEKGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
